baseURL = "https://despreston.github.io/"
languageCode = "en-us"
title = "Des Preston"
theme = "smol"

# Parameters
[params]
    dateFmt = "02.01.2006 15:04"
    customCSS = ["css/custom.css"]

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/despreston"
        weight = 1

    [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/despreston"
        weight = 2
